### ISSUE TITLE
How do I increase "tire grip" and reduce sliding?

### ISSUE THREAD

**Issue by brickyt** [stesim/godot-vehicle-sandbox#2]
Amazing job with this vehicle controller! Best godot vehicle demo I've seen out there!

I am going for a simcade feel for my prototype and wanting to reduce the amount of sliding/slipping when the car is at high speeds and turning fully left or right.

Any help or tips would be most appreciated! Cheers!

**Comment by stesim** [comment]
The `traction_limit`, `longitudinal_traction_curve_scale.y` and `lateral_traction_curve_scale.y` properties of the tires are probably what you're looking for. Try setting them to a higher value, maybe something like 1.5 as a start. `longitudinal_traction_curve_scale.y` affects acceleration and braking, whereas `lateral_traction_curve_scale.y` affects steering. They don't have to be equal, but `traction_limit` should normally be set to the larger of the two curve scale values.

You'd probably also want to lower the vehicle's center of mass, otherwise it will roll a lot due to the high grip forces.
